### ISSUE TITLE
Performance issues & Production environment use

### ISSUE THREAD

**Issue by xiaochai1027** [go-echarts/statsview#14]
hi.
I want to integrate it into my services。
My service is a high performance live streaming service。
I see that your program will call periodically (Runtime.ReadMemStats()).

This method says in the source code：

```
	stopTheWorld("read mem stats")

	systemstack(func() {
		readmemstats_m(m)
	})

	startTheWorld()
```
Looks like it will pause the program to collect information, shouldn't it be used in production?

**Comment by xiaochai1027** [comment]
I now consider dynamically creating and destroying this monitoring service by using the HTTP service exposed interface.

Use it only when you want to.

Do we need to do that?

**Comment by chenjiandongx** [comment]
@xiaochai1027 You can call the `Start()` function when you need to show the runtime stats and call the `Stop()` in the end.

`runtime.ReadMemStats` did actually STOP THE WORLD, but I think if it uses as needed will not cause the perfromance issue

**Comment by xiaochai1027** [comment]
ok.
That's how it works now.

**Comment by xiaochai1027** [comment]
In use, I found that I wanted the (start) method to return a service listener error.
This is very helpful for online service startup to find problems.
A successful method call occurs, but the service is not started

**Comment by chenjiandongx** [comment]
@xiaochai1027 https://github.com/go-echarts/statsview/pull/15

**Comment by chenjiandongx** [comment]
Fixed -> https://github.com/go-echarts/statsview/issues/13
