### ISSUE TITLE
GC Number

### ISSUE THREAD

**Issue by gandaldf** [go-echarts/statsview#19]
Hi, this isn't exactly an issue, I'd just like to have an explaination about what is the "GC Number" in the charts.
Is it the number of garbage collection cycles? My app have an always increasing "GC Number" and I would like to know if this could be a problem.

Thank you.

**Comment by chenjiandongx** [comment]
@gandaldf 

![image](https://user-images.githubusercontent.com/19553554/129698210-88a6e559-fef8-4440-8a2e-6ca33739bc2e.png)

**Comment by gandaldf** [comment]
Thank you @chenjiandongx, so it's normal that it always reports an increasing number, right?

**Comment by chenjiandongx** [comment]
yes, it's a monotonic increasing variable.

**Comment by gandaldf** [comment]
Ok! Thank you!
