### ISSUE TITLE
feature request: instead of port number have a route

### ISSUE THREAD

**Issue by Gys** [go-echarts/statsview#2]
Hi!

The access to the graphs is now by using a special port number. This is ok for local apps, but difficult for apps deployed remotely. Because those are behind firewalls and stuff. Or, in the case of Heroku, it is not possible to open (or select) a second port. A special route like '/debug/vars' would work better in those cases.

**Comment by chenjiandongx** [comment]
PING @Gys 

The std profiler has been integrated into statsview since [v0.2.0](https://github.com/go-echarts/statsview/commit/441636fd25e421458d4497fc12d99e4fa62c5f0e) hence you can use statsview as the only profiler on your program now. :)

Enjoy it!

**Comment by Gys** [comment]
Aha, sorry, did only see the port mentioned in the docs!
