### ISSUE TITLE
Feature Request: more details when mouse hover on lines

### ISSUE THREAD

**Issue by jim3ma** [go-echarts/statsview#3]
Like this:
<img width="738" alt="Screen Shot 2020-11-18 at 10 58 55" src="https://user-images.githubusercontent.com/1567113/99477287-29012300-298d-11eb-83f3-5edddd987123.png">

**Comment by chenjiandongx** [comment]
@jim3ma v0.3.0 has been released and more detailed info will be displayed when the mouse hover. 

![](https://user-images.githubusercontent.com/19553554/99491359-92d9f680-29a6-11eb-99c8-bc333cb90893.png)
