### ISSUE TITLE
 Can add custom routing function

### ISSUE THREAD

**Issue by sxueck** [go-echarts/statsview#4]
Can add a custom routing function, like this
```
viewer.SetConfiguration(viewer.WithTheme(viewer.ThemeWalden), viewer.WithAddr("localhost:8087"),viewer.WithViewPath("/"))
```

**Comment by sxueck** [comment]
I made some changes, but it doesn’t seem to be very compatible
https://github.com/sxueck/statsview

**Comment by chenjiandongx** [comment]
@sxueck What's your purpose  setting this option?

**Comment by sxueck** [comment]
I try to use the echo framework to reverse proxy this path(`/debug/viewstaic`)
But he told me that I can only proxy the root path(`/`)

**Comment by chenjiandongx** [comment]
@sxueck You can transform statsview by yourself as I don't want to provide the feature mentioned :)

I think it would be a better choice to keep the same route-prefix with the std `net/http/pprof`
