### ISSUE TITLE
Missing Charts

### ISSUE THREAD

**Issue by JetSetIlly** [go-echarts/statsview#5]
One of my users is reporting that he cannot see all the statsview charts on Windows. He's tried it on a couple of browsers with the same results. These are the screenshots he's given me:

![firefox](https://user-images.githubusercontent.com/58750902/99909081-46f8bb80-2cde-11eb-9227-298e1dd86b7f.png)

![chrome](https://user-images.githubusercontent.com/58750902/99909086-4eb86000-2cde-11eb-8d81-bbc8868c5d3c.png)

I don't have access to Windows here so it is difficult to debug. Is this a known problem?

Project here:

https://github.com/JetSetIlly/Gopher2600

**Comment by chenjiandongx** [comment]
@JetSetIlly Try to use the statsview latest version v0.3.1 which has fixed this issue on Windows

**Comment by JetSetIlly** [comment]
Yes. That fixes it. Thanks.
