### ISSUE TITLE
ThemeWalden not declared by package viewer

### ISSUE THREAD

**Issue by robtrooper** [go-echarts/statsview#7]
Running statsview with the recomended configuration is giving me an error
ThemeWalden not declared by package viewer

I'm adding it as suggested before calling Start() but it seems to be missing something.

	go func() {
		mgr := statsview.New()

		viewer.SetConfiguration(viewer.WithTheme(viewer.ThemeWalden), view.WithAddr("localhost:8087"))

		// Start() runs a HTTP server at `localhost:18066` by default.
		mgr.Start()

Gives me 
ThemeWalden not declared by package viewer

When expecting to see a different theme and port.

Also not seeing more than two views when omitting the viewer line. I'm seeing Goroutines and Heap but not the others listed.

**Comment by chenjiandongx** [comment]
statsview only provides two themes `ThemeWesteros` / `ThemeMacarons` and I seem forgot to update the docs.

Documentation has been corrected now.
