### ISSUE TITLE
feat: separate listening address from access address.

### ISSUE THREAD

**Issue by ocean2811** [go-echarts/statsview#8]
Hi: 
        Our golang applications are deployed in an intranet environment.  Users need to access pprof interface by proxy. So we need separate listening address from access address. I have a commit https://github.com/ocean2811/statsview/commit/38d0c35dc2599141d426eab34bbcb6883c7914c9 that implements the feature.

**Comment by chenjiandongx** [comment]
@ocean2811 

Hi, the feature you mentioned looks good to me, but should we retain the `WithAddr` function for compatibility?

If users don't want to separate the listening address and link address, they could use `WithAddr` instead

**Comment by ocean2811** [comment]
Sorry for not replying in time.  I think you are right. So we should only add a function to cover the html link address.
