### ISSUE TITLE
Enable CORS for remote debugging

### ISSUE THREAD

**Issue by oldkingsquid** [go-echarts/statsview#9]
When i am running a VM with a go application but want to see the results on the host machine, the frontend won't load due to CORS.

**Comment by chenjiandongx** [comment]
Try to modify [this line](https://github.com/go-echarts/statsview/blob/master/statsview.go#L135) of code, use `mgr.srv.Handler = cors.AllowAll().Handler(mux)` instead.

**Comment by oldkingsquid** [comment]
Awesome, this is perfect. Thanks!
